apiVersion: scaffolder.backstage.io/v1beta3
kind: Component
metadata:
    name: {{ cookiecutter.name }}
    title: {{ cookiecutter.title }}
    description: {{ cookiecutter.description }}
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: {{ cookiecutter.destination.owner }}/{{ cookiecutter.destination.repo }}

spec:
    type: documentation
    lifecycle: development
    owner: {{ cookiecutter.owner }}
