apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: educacao
  description: Time responsável por criar sistemas multiagente que buscam impactar positivamente a área educacional.
spec:
  type: team
  profile:
    displayName: Educação
    email: agents4good@gmail.com
  children: []