apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: fundacao
  description: Time responsável por definir padrões de documentação e nomenclatura; gerenciar repositórios e artefatos no portal da organização; pesquisar, estudar e criar modelos de linguagem confiáveis e modos de usá-los.
spec:
  type: team
  profile:
    displayName: Fundação
    email: agents4good@gmail.com
  children: []