apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: daniel-mantovani
spec:
  profile:
    displayName: Daniel Mantovani
    email: daniel.@ccc.ufcg.edu.br
    picture: https://avatars.githubusercontent.com/u/103224655
  memberOf: [geracao]