apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: eyshila-buriti
  profile:
    displayName: Eyshila Buriti
    email: eyshila.buriti.araujo.azevedo@ccc.ufcg.edu.br
    picture: https://avatars.githubusercontent.com/u/105816646
  memberOf: [desinformacao]