apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gabriel-guimaraes
spec:
  profile:
    displayName: Gabriel Guimarães
    email: gabriel.souza@ccc.ufcg.edu.br
    picture: https://avatars.githubusercontent.com/u/115805499
  memberOf: [geracao]