apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: joao-pedro
spec:
  profile:
    displayName: João Pedro
    email: joao.pedro.angelo@ccc.ufcg.edu.br
    picture: https://avatars.githubusercontent.com/u/155973507
  memberOf: [fundacao]